services:
  panel:
    image: c0w0c/clover-panel
    container_name: panel
    ports:
     - 82:80
    volumes:
      - ./db:/app/db
      - ./config:/app/config
      - logo_data:/app/logo
volumes:
  logo_data:
